name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Debug repository structure
      - name: Debug repository structure
        run: |
          ls -l /home/runner/work/pod

      # Install dependencies
      - name: Install dependencies
        run: |
          cd /home/runner/work/pod/Backend
          npm ci

      # Build the project
      - name: Build project
        run: |
          cd /home/runner/work/pod/Backend
          npm run build --if-present

      # Start the project
      - name: Start project
        run: |
          cd /home/runner/work/pod/Backend
          npm start
