name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Debug repository structure
      - name: Debug repository structure
        run: |
          ls -l /home/runner/work/pod

      # Install dependencies
      - name: Install dependencies
        run: |
          cd /home/runner/work/pod/pod/Backend
          npm ci

      # Start the project
      - name: Start the server
        run: |
          cd /home/runner/work/pod/pod/Backend
          npm start &  # Run the server in the background
          sleep 10     # Wait for 10 seconds (or however long you need to test the server)
          kill %1      # Stop the background server process
