name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Debug directory structure to confirm paths
      - name: Debug directory structure
        run: |
          ls /home/runner/work/pod
          ls /home/runner/work/pod/Backend

      # Install dependencies for Backend
      - name: Install dependencies
        run: |
          cd /home/runner/work/pod/Backend
          npm ci

      # Build the project
      - name: Build project
        run: |
          cd /home/runner/work/pod/Backend
          npm run build --if-present

      # Start the project
      - name: Start project
        run: |
          cd /home/runner/work/pod/Backend
          npm start
