name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          cd /home/runner/work/pod/Backend
          npm ci

      # Install additional dependencies (optional if npm ci covers it)
      - name: Install additional packages
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build --if-present

      # Start the project
      - name: Start project
        run: npm start
